<?php
/**
 * Source by eGooTY - https://egooty.com
 *
 * @category    Egooty
 * @package     Egooty_SeoToolkits
 * @author      Mudassar Ali <sahil_bwp@yahoo.com>
 * @author      eGooTY <dev@egooty.com>
 * @copyright   Copyright (c) eGooTY Pvt. (https://egooty.com)
 * @license     https://egooty.com/source-legal-information/ eGooTY End User License Agreement
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 */

use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(
    ComponentRegistrar::MODULE,
    'Egooty_SeoToolkits',
    __DIR__
);
