<?php
/**
 * Source by eGooTY - https://egooty.com
 *
 * @category    Egooty
 * @package     Egooty_SeoToolkits
 * @author      Mudassar Ali <sahil_bwp@yahoo.com>
 * @author      eGooTY <dev@egooty.com>
 * @copyright   Copyright (c) eGooTY Pvt. (https://egooty.com)
 * @license     https://egooty.com/source-legal-information/ eGooTY End User License Agreement
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 */
declare(strict_types=1);

namespace Egooty\SeoToolkits\Model\Config\Source;

use Magento\Framework\Option\ArrayInterface;
use Magento\Store\Model\StoreManagerInterface;

class EnableLocale implements ArrayInterface
{
    /**
     * @var StoreManagerInterface
     */
    private $storeManager;

    /**
     * DisableLocale constructor.
     *
     * @param StoreManagerInterface $storeManager
     */
    public function __construct(StoreManagerInterface $storeManager)
    {
        $this->storeManager = $storeManager->getStores();
    }

    /**
     * @inheritdoc
     */
    public function toOptionArray()
    {
        foreach ($this->storeManager as $store) {
            $storeList[] = [
                'value' => $store->getCode(),
                'label' => __($store->getName())
            ];
        }

        return $storeList;
    }

    /**
     * @inheritdoc
     */
    public function toArray()
    {
        foreach ($this->storeManager as $store) {
            $storeList[] = [
                $store->getCode() => __($store->getName())
            ];
        }

        return $storeList;
    }
}
